spring:
  application:
    name: gestion_pharmacie
  datasource:
    url: ${DATABASE_URL}
    password: ${PASSWORD}
    username: ${USER}
  jpa:
    hibernate:
      ddl-auto: create

  profiles:
    active: mysql, emailApprenant

logging:
  level:
    root: info
    sql: warn
    web: warn






